# Generated by Django 4.1.4 on 2022-12-23 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="monitor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
