# Generated by Django 4.1.4 on 2022-12-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0002_monitor_created_at_monitor_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monitor",
            old_name="price",
            new_name="current_price",
        ),
    ]
